# Databricks notebook source
# MAGIC %md
# MAGIC **Notebook name:** initialize
# MAGIC **Functionality:** initializes the necessary configuration values for the rest of the process into a json

# COMMAND ----------

# MAGIC %run ./common

# COMMAND ----------

# replace values for accounts exec
hostname = (
    dbutils.notebook.entry_point.getDbutils()
    .notebook()
    .getContext()
    .apiUrl()
    .getOrElse(None)
)
cloud_type = getCloudType(hostname)

# COMMAND ----------

# MAGIC %md
# MAGIC ##### Modify JSON values
# MAGIC * **account_id** Account ID. Can get this from the accounts console
# MAGIC * **sql_warehouse_id** SQL Warehouse ID to import dashboard
# MAGIC * **verbosity** (optional). debug, info, warning, error, critical
# MAGIC * **maxpages** for paginated calls, how many max pages to iterate before stopping
# MAGIC * **timebetweencalls** time in secs between api calls. This is to prevent rejections with too many api calls
# MAGIC * **master_name_scope** Secret Scope for Account Name
# MAGIC * **master_name_key** Secret Key for Account Name
# MAGIC * **master_pwd_scope** Secret Scope for Account Password
# MAGIC * **master_pwd_key** Secret Key for Account Password
# MAGIC * **workspace_pat_scope** Secret Scope for Workspace PAT
# MAGIC * **workspace_pat_token_prefix** Secret Key prefix for Workspace PAT. Workspace ID will automatically be appended to this per workspace
# MAGIC * **use_mastercreds** (optional) Use master account credentials for all workspaces
# MAGIC * **sat_version** Version of the SAT version being used

# COMMAND ----------

SECRETS_SCOPE = "sat_scope"

# COMMAND ----------

import json

json_ = {
    "account_id": dbutils.secrets.get(scope=SECRETS_SCOPE, key="account-console-id"),
    "sql_warehouse_id": dbutils.secrets.get(scope=SECRETS_SCOPE, key="sql-warehouse-id"),
    "analysis_schema_name": dbutils.secrets.get(
        scope=SECRETS_SCOPE, key="analysis_schema_name"
    ),
    "verbosity": "info",
    "maxpages":10,
    "timebetweencalls":1,
    "proxies": json.loads(dbutils.secrets.get(scope=SECRETS_SCOPE, key="proxies")),
}

# COMMAND ----------

# MAGIC %md
# MAGIC ##### Intermediate Schema Creation
# MAGIC The following section creates an intermediate schema for storing temporary tables. Previously, these were created as global temp views, but since serverless does not support global temp views, they are now created as tables.

# COMMAND ----------

intermediate_schema_name = (
    f"{json_['analysis_schema_name'].split('.')[0]}.intermediate_schema"
    if '.' in json_['analysis_schema_name']
    else "hive_metastore.intermediate_schema"
)
json_.update(
    {
        "intermediate_schema" : intermediate_schema_name
    }

)

# COMMAND ----------

json_.update(
    {
        "master_name_scope": SECRETS_SCOPE,
        "master_name_key": "user",
        "master_pwd_scope": SECRETS_SCOPE,
        "master_pwd_key": "pass",
        "workspace_pat_scope": SECRETS_SCOPE,
        "workspace_pat_token_prefix": "sat-token",
        "dashboard_id": "317f4809-8d9d-4956-a79a-6eee51412217",
        "dashboard_folder": f"{basePath()}/dashboards/",
        "dashboard_tag": "SAT",
        "use_mastercreds": True,
        "use_parallel_runs": True,
        # accounts_console: URL for accounts console in special environments (gov cloud, DoD)
        # Leave empty for standard environments. Examples:
        #   - GovCloud (FedRAMP): "https://accounts.cloud.databricks.us"
        #   - DoD (IL4/IL5): See https://docs.databricks.com/aws/en/security/privacy/gov-cloud
        "accounts_console": "",
        "sat_version": "0.7.0",
    }
)


# COMMAND ----------

# DBTITLE 1,GCP configurations
if cloud_type == "gcp":
    sp_auth = {
        "use_sp_auth": "False",
        "client_id": "",
        "client_secret_key": "client-secret",
    }
    try:
        use_sp_auth = (
            dbutils.secrets.get(scope=SECRETS_SCOPE, key="use-sp-auth").lower() == "true"
        )
        if use_sp_auth:
            sp_auth["use_sp_auth"] = "True"
            sp_auth["client_id"] = dbutils.secrets.get(
                scope=SECRETS_SCOPE, key="client-id"
            )
    except:
        pass
    json_.update(sp_auth)

# COMMAND ----------

# DBTITLE 1,Azure configurations
if cloud_type == "azure":
    json_.update(
        {
            "subscription_id": dbutils.secrets.get(
                scope=SECRETS_SCOPE, key="subscription-id"
            ),  # Azure subscriptionId
            "tenant_id": dbutils.secrets.get(
                scope=SECRETS_SCOPE, key="tenant-id"
            ),  # The Directory (tenant) ID for the application registered in Azure AD.
            "client_id": dbutils.secrets.get(
                scope=SECRETS_SCOPE, key="client-id"
            ),  # The Application (client) ID for the application registered in Azure AD.
            "client_secret_key": "client-secret",  # The secret generated by AAD during your confidential app registration
            "use_mastercreds": True,
        }
    )


# COMMAND ----------

# DBTITLE 1,AWS configurations
if cloud_type == "aws":
    sp_auth = {
        "use_sp_auth": "False",
        "client_id": "",
        "client_secret_key": "client-secret",
    }
    try:
        use_sp_auth = (
            dbutils.secrets.get(scope=SECRETS_SCOPE, key="use-sp-auth").lower() == "true"
        )
        if use_sp_auth:
            sp_auth["use_sp_auth"] = "True"
            sp_auth["client_id"] = dbutils.secrets.get(
                scope=SECRETS_SCOPE, key="client-id"
            )
    except:
        pass
    json_.update(sp_auth)

# COMMAND ----------

# COMMAND ----------

# DBTITLE 1,Overrides de ambiente via parametros do bundle (nao-secretos)
# Config nao secreta pode chegar como job parameter do Databricks Asset Bundle
# (Declarative Automation Bundles) e sobrescreve o default. Segredo continua vindo
# do secret scope acima. Se rodar interativo, sem parametros, mantem o default.
def _bundle_param(name):
    try:
        v = dbutils.widgets.get(name)
        return v if v not in (None, "") else None
    except Exception:
        return None

_ov = {k: _bundle_param(k) for k in (
    "analysis_schema_name", "maxpages", "timebetweencalls",
    "use_parallel_runs", "secrets_max_parallel_workspaces",
)}
for _k, _v in _ov.items():
    if _v is not None:
        json_[_k] = _v

# widgets chegam como string: converte os numericos e o booleano
for _k in ("maxpages", "timebetweencalls", "secrets_max_parallel_workspaces"):
    if isinstance(json_.get(_k), str):
        json_[_k] = int(json_[_k])
if isinstance(json_.get("use_parallel_runs"), str):
    json_["use_parallel_runs"] = json_["use_parallel_runs"].strip().lower() == "true"

# re-deriva o intermediate_schema caso o catalogo/schema tenha mudado
json_["intermediate_schema"] = (
    f"{json_['analysis_schema_name'].split('.')[0]}.intermediate_schema"
    if "." in json_["analysis_schema_name"] else "hive_metastore.intermediate_schema"
)

# Fail-closed: em execucao de job do bundle o schema DEVE vir por parametro.
# Sem widget, o valor acima veio do secret scope — que pode apontar para o
# schema de OUTRA instalacao (ex.: producao). Falhar aqui e barato; escrever
# no schema errado nao e.
if _ov.get("analysis_schema_name") is None:
    import os as _os
    if _os.environ.get("SAT_ALLOW_SCOPE_SCHEMA", "").lower() != "true":
        raise Exception(
            "analysis_schema_name nao foi informado por parametro (widget). "
            "Rode via job do bundle, ou passe o widget manualmente, ou defina "
            "SAT_ALLOW_SCOPE_SCHEMA=true para aceitar conscientemente o valor do scope: "
            f"{json_['analysis_schema_name']}"
        )

# COMMAND ----------


from core.logging_utils import LoggingUtils

LoggingUtils.set_logger_level(LoggingUtils.get_log_level(json_["verbosity"]))
loggr = LoggingUtils.get_logger()

# COMMAND ----------

#spark.sql(f"DROP DATABASE IF EXISTS {json_['intermediate_schema']} CASCADE")

# COMMAND ----------

create_schema()
create_security_checks_table()
create_account_info_table()
create_account_workspaces_table()
create_notebooks_secret_scan_results_table()
create_clusters_secret_scan_results_table()
create_workspace_run_complete_table()

# COMMAND ----------

# Initialize best practices
readBestPracticesConfigsFile()

# COMMAND ----------

# Initialize sat dasf mapping
load_sat_dasf_mapping()

